volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql
